### ISSUE TITLE
Missing Domains

### ISSUE THREAD

**Issue by diablodaz** [cybersectech-org/urlinsane#41]
Great tool and very fast, however for coverage the following tool finds far more domains:

https://labs.nccgroup.trust/typofinder/
https://github.com/nccgroup/typofinder

Would love to see these functions incorporated into urlinsane

**Comment by talhachi** [comment]
Nice, thanks for letting us know. Will start adding these functions. If you have any ideas of functions not implemented or mentioned in our GitHub issues please let us know.

**Comment by talhachi** [comment]
@diablodaz @jubairsaidi  It looks like subdomain insertion was missing in urlinsane. I just submitted a PR to add that. For "google.com" typo finder finds 171 live domains and urlinsane now finds 1456 live domains. It's amazing how many domains are registered with this type of function.  Thanks for bringing this to our attention. PR: https://github.com/cybersectech-org/urlinsane/pull/44

**Comment by talhachi** [comment]
one thing we can also add is a tld insertion function such as googlecom.com googlenet.net or even googlecom.net

**Comment by diablodaz** [comment]
Also - and . characters across the domain name e.g.

Ama-zon.co.uk
Ama.zon.co.uk

**Comment by talhachi** [comment]
Added to issue: https://github.com/cybersectech-org/urlinsane/issues/48

**Comment by jubairsaidi** [comment]
Closing this ticket in favor of the other specific implementation issues opened.
